import { db } from '@/db';
import { members } from '@/db/schema';

async function main() {
    // Delete existing members first
    await db.delete(members);

    const sampleMembers = [
        // Workshop Participants (10 members)
        {
            userId: null,
            firstName: 'Marcus',
            lastName: 'Thompson',
            email: 'marcus.thompson@gmail.com',
            phone: '(303) 555-0142',
            address: '1245 Federal Blvd',
            city: 'Denver',
            state: 'CO',
            zipCode: '80204',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['leadership_development', 'trauma_recovery', 'peer_mentorship']),
            notes: 'LDI Tier 1 participant. Completed 3 workshops. Strong engagement in leadership development.',
            joinedAt: new Date('2024-03-15').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: null,
            firstName: 'LaShonda',
            lastName: 'Williams',
            email: 'lashonda.w@yahoo.com',
            phone: '(720) 555-0198',
            address: '3421 Colfax Ave',
            city: 'Denver',
            state: 'CO',
            zipCode: '80206',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['trauma_recovery', 'biblical_studies', 'life_skills']),
            notes: 'Attending trauma recovery workshops. Making excellent progress. Completed AWAKEN series.',
            joinedAt: new Date('2024-02-10').toISOString(),
            lastActivityAt: new Date('2024-12-18').toISOString(),
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            userId: null,
            firstName: 'Carlos',
            lastName: 'Rodriguez',
            email: 'carlos.rodriguez@gmail.com',
            phone: '(303) 555-0267',
            address: '892 Broadway',
            city: 'Denver',
            state: 'CO',
            zipCode: '80203',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['leadership_development', 'career_development', 'life_skills']),
            notes: 'EQUIP workshop series participant. Interested in becoming peer mentor. Strong leadership potential.',
            joinedAt: new Date('2024-05-22').toISOString(),
            lastActivityAt: new Date('2024-12-21').toISOString(),
            createdAt: new Date('2024-05-22').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: null,
            firstName: 'Keisha',
            lastName: 'Jackson',
            email: 'keisha.jackson@gmail.com',
            phone: '(720) 555-0334',
            address: '2156 Lincoln St',
            city: 'Aurora',
            state: 'CO',
            zipCode: '80010',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['biblical_studies', 'trauma_recovery', 'spiritual_growth']),
            notes: 'Participating in weekly biblical studies workshops. Very engaged in group discussions.',
            joinedAt: new Date('2024-04-08').toISOString(),
            lastActivityAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-04-08').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: null,
            firstName: 'DeShawn',
            lastName: 'Miller',
            email: 'deshawn.miller@yahoo.com',
            phone: '(303) 555-0445',
            address: '4567 Downing St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80218',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['leadership_development', 'peer_mentorship', 'career_development']),
            notes: 'LDI Tier 2 participant. Completed mentor training. Now co-facilitating workshops.',
            joinedAt: new Date('2024-01-20').toISOString(),
            lastActivityAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: null,
            firstName: 'Maria',
            lastName: 'Gonzalez',
            email: 'maria.gonzalez@gmail.com',
            phone: '(720) 555-0556',
            address: '789 Federal Blvd',
            city: 'Lakewood',
            state: 'CO',
            zipCode: '80226',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['life_skills', 'financial_literacy', 'career_development']),
            notes: 'Attending life skills and financial literacy workshops. Excellent attendance record.',
            joinedAt: new Date('2024-06-12').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-06-12').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: null,
            firstName: 'Jamal',
            lastName: 'Harris',
            email: 'jamal.harris@gmail.com',
            phone: '(303) 555-0623',
            address: '2341 York St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80205',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['trauma_recovery', 'peer_mentorship', 'biblical_studies']),
            notes: 'Active in AWAKEN trauma recovery workshops. 6 months progress. Sharing testimony in upcoming workshop.',
            joinedAt: new Date('2024-07-18').toISOString(),
            lastActivityAt: new Date('2024-12-21').toISOString(),
            createdAt: new Date('2024-07-18').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: null,
            firstName: 'Carmen',
            lastName: 'Sanchez',
            email: 'carmen.s@yahoo.com',
            phone: '(720) 555-0789',
            address: '5678 Sheridan Blvd',
            city: 'Arvada',
            state: 'CO',
            zipCode: '80002',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['leadership_development', 'life_skills', 'biblical_studies']),
            notes: 'Completed LDI Tier 1. Strong group leader. Interested in facilitator training.',
            joinedAt: new Date('2024-08-05').toISOString(),
            lastActivityAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-08-05').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: null,
            firstName: 'Tyrone',
            lastName: 'Washington',
            email: 'tyrone.washington@gmail.com',
            phone: '(303) 555-0834',
            address: '1023 Colorado Blvd',
            city: 'Denver',
            state: 'CO',
            zipCode: '80220',
            memberType: 'workshop_participant',
            status: 'active',
            interests: JSON.stringify(['career_development', 'life_skills', 'peer_mentorship']),
            notes: 'Career development workshops participant. Recently completed job readiness training. Seeking employment.',
            joinedAt: new Date('2024-09-14').toISOString(),
            lastActivityAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-09-14').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: null,
            firstName: 'Tanya',
            lastName: 'Brown',
            email: 'tanya.brown@gmail.com',
            phone: '(720) 555-0912',
            address: '3456 Monaco Pkwy',
            city: 'Denver',
            state: 'CO',
            zipCode: '80207',
            memberType: 'workshop_participant',
            status: 'inactive',
            interests: JSON.stringify(['biblical_studies', 'trauma_recovery', 'spiritual_growth']),
            notes: 'Completed AWAKEN series in October. Moved to Colorado Springs. Excellent testimonial for program.',
            joinedAt: new Date('2024-04-25').toISOString(),
            lastActivityAt: new Date('2024-10-15').toISOString(),
            createdAt: new Date('2024-04-25').toISOString(),
            updatedAt: new Date('2024-10-15').toISOString(),
        },

        // Outreach Participants (5 members)
        {
            userId: null,
            firstName: 'Luis',
            lastName: 'Martinez',
            email: 'luis.martinez@gmail.com',
            phone: '(303) 555-1023',
            address: '2789 Santa Fe Dr',
            city: 'Denver',
            state: 'CO',
            zipCode: '80223',
            memberType: 'outreach_participant',
            status: 'active',
            interests: JSON.stringify(['food_assistance', 'housing_support', 'job_training']),
            notes: 'Case Manager: Sarah Johnson. Receiving weekly NOURISH food assistance. Housing voucher application in progress.',
            joinedAt: new Date('2024-08-30').toISOString(),
            lastActivityAt: new Date('2024-12-21').toISOString(),
            createdAt: new Date('2024-08-30').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: null,
            firstName: 'Tamika',
            lastName: 'Johnson',
            email: 'tamika.j@yahoo.com',
            phone: '(720) 555-1134',
            address: '4123 Peoria St',
            city: 'Aurora',
            state: 'CO',
            zipCode: '80011',
            memberType: 'outreach_participant',
            status: 'active',
            interests: JSON.stringify(['transportation', 'food_assistance', 'financial_literacy']),
            notes: 'Case Manager: Michael Davis. Active in TRANSIT program. Receiving transportation support for job interviews.',
            joinedAt: new Date('2024-09-12').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-09-12').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: null,
            firstName: 'Andre',
            lastName: 'Davis',
            email: 'andre.davis@gmail.com',
            phone: '(303) 555-1245',
            address: '567 Chambers Rd',
            city: 'Aurora',
            state: 'CO',
            zipCode: '80012',
            memberType: 'outreach_participant',
            status: 'active',
            interests: JSON.stringify(['housing_support', 'job_training', 'food_assistance']),
            notes: 'Case Manager: Lisa Chen. HAVEN housing support recipient. Secured transitional housing November 2024.',
            joinedAt: new Date('2024-07-08').toISOString(),
            lastActivityAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-07-08').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: null,
            firstName: 'Patricia',
            lastName: 'Lewis',
            email: 'patricia.lewis@yahoo.com',
            phone: '(720) 555-1356',
            address: '890 Havana St',
            city: 'Aurora',
            state: 'CO',
            zipCode: '80010',
            memberType: 'outreach_participant',
            status: 'active',
            interests: JSON.stringify(['food_assistance', 'financial_literacy', 'job_training']),
            notes: 'Case Manager: Sarah Johnson. Weekly NOURISH participant. Completed financial literacy workshop series.',
            joinedAt: new Date('2024-10-05').toISOString(),
            lastActivityAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-10-05').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: null,
            firstName: 'Jerome',
            lastName: 'Anderson',
            email: 'jerome.anderson@gmail.com',
            phone: '(303) 555-1467',
            address: '1234 Quebec St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80220',
            memberType: 'outreach_participant',
            status: 'active',
            interests: JSON.stringify(['transportation', 'housing_support', 'job_training']),
            notes: 'Case Manager: Michael Davis. TRANSIT and HAVEN participant. Needs transportation for new job starting January.',
            joinedAt: new Date('2024-11-02').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-11-02').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },

        // Ministry Volunteers (5 members)
        {
            userId: null,
            firstName: 'David',
            lastName: 'Mitchell',
            email: 'david.mitchell@gmail.com',
            phone: '(303) 555-1578',
            address: '4567 University Blvd',
            city: 'Denver',
            state: 'CO',
            zipCode: '80210',
            memberType: 'ministry_volunteer',
            status: 'active',
            interests: JSON.stringify(['mentorship', 'workshop_facilitation', 'counseling']),
            notes: 'Approved volunteer - Background check complete. Certified counselor. Leads trauma recovery groups every Tuesday.',
            joinedAt: new Date('2024-01-10').toISOString(),
            lastActivityAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: null,
            firstName: 'Angela',
            lastName: 'Roberts',
            email: 'angela.roberts@gmail.com',
            phone: '(720) 555-1689',
            address: '789 Colorado Blvd',
            city: 'Denver',
            state: 'CO',
            zipCode: '80206',
            memberType: 'ministry_volunteer',
            status: 'active',
            interests: JSON.stringify(['food_distribution', 'administrative', 'mentorship']),
            notes: 'Approved volunteer - Background check complete. Coordinates NOURISH food distribution. 3 years service.',
            joinedAt: new Date('2024-02-15').toISOString(),
            lastActivityAt: new Date('2024-12-21').toISOString(),
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: null,
            firstName: 'Robert',
            lastName: 'Taylor',
            email: 'robert.taylor@gmail.com',
            phone: '(303) 555-1790',
            address: '2345 Evans Ave',
            city: 'Denver',
            state: 'CO',
            zipCode: '80210',
            memberType: 'ministry_volunteer',
            status: 'active',
            interests: JSON.stringify(['workshop_facilitation', 'mentorship', 'counseling']),
            notes: 'Approved volunteer - Background check complete. LDI workshop facilitator. Former United Convicts participant.',
            joinedAt: new Date('2024-03-20').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: null,
            firstName: 'Michelle',
            lastName: 'Wright',
            email: 'michelle.wright@gmail.com',
            phone: '(720) 555-1801',
            address: '5678 Alameda Ave',
            city: 'Lakewood',
            state: 'CO',
            zipCode: '80226',
            memberType: 'ministry_volunteer',
            status: 'active',
            interests: JSON.stringify(['mentorship', 'administrative', 'workshop_facilitation']),
            notes: 'Approved volunteer - Background check complete. Peer mentorship coordinator. Manages volunteer schedules.',
            joinedAt: new Date('2024-05-08').toISOString(),
            lastActivityAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-05-08').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: null,
            firstName: 'Thomas',
            lastName: 'King',
            email: 'thomas.king@gmail.com',
            phone: '(303) 555-1912',
            address: '890 Morrison Rd',
            city: 'Denver',
            state: 'CO',
            zipCode: '80219',
            memberType: 'ministry_volunteer',
            status: 'active',
            interests: JSON.stringify(['food_distribution', 'transportation', 'mentorship']),
            notes: 'Approved volunteer - Background check complete. TRANSIT driver and food distribution volunteer. Reliable servant leader.',
            joinedAt: new Date('2024-06-25').toISOString(),
            lastActivityAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-06-25').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },

        // Newsletter Subscribers (5 members)
        {
            userId: null,
            firstName: 'Jennifer',
            lastName: 'Garcia',
            email: 'jennifer.garcia@gmail.com',
            phone: '(720) 555-2023',
            address: null,
            city: null,
            state: null,
            zipCode: null,
            memberType: 'newsletter_subscriber',
            status: 'active',
            interests: JSON.stringify(['ministry_updates', 'events', 'testimonies']),
            notes: 'Subscribed via website 11/2024. Interested in volunteer opportunities.',
            joinedAt: new Date('2024-11-15').toISOString(),
            lastActivityAt: new Date('2024-12-15').toISOString(),
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
        },
        {
            userId: null,
            firstName: 'Steven',
            lastName: 'Moore',
            email: 'steven.moore@yahoo.com',
            phone: null,
            address: null,
            city: null,
            state: null,
            zipCode: null,
            memberType: 'newsletter_subscriber',
            status: 'active',
            interests: JSON.stringify(['ministry_updates', 'prayer_requests']),
            notes: 'Subscribed via website 09/2024. Faithful prayer partner.',
            joinedAt: new Date('2024-09-20').toISOString(),
            lastActivityAt: new Date('2024-12-18').toISOString(),
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            userId: null,
            firstName: 'Rachel',
            lastName: 'White',
            email: 'rachel.white@gmail.com',
            phone: '(303) 555-2134',
            address: null,
            city: null,
            state: null,
            zipCode: null,
            memberType: 'newsletter_subscriber',
            status: 'active',
            interests: JSON.stringify(['events', 'testimonies', 'prayer_requests']),
            notes: 'Referred by volunteer Angela Roberts. Attends quarterly community events.',
            joinedAt: new Date('2024-08-10').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-08-10').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: null,
            firstName: 'Brian',
            lastName: 'Hall',
            email: 'brian.hall@yahoo.com',
            phone: null,
            address: null,
            city: null,
            state: null,
            zipCode: null,
            memberType: 'newsletter_subscriber',
            status: 'active',
            interests: JSON.stringify(['ministry_updates', 'events']),
            notes: 'Subscribed via website 07/2024. Monthly financial supporter.',
            joinedAt: new Date('2024-07-22').toISOString(),
            lastActivityAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-07-22').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: null,
            firstName: 'Sandra',
            lastName: 'Allen',
            email: 'sandra.allen@gmail.com',
            phone: '(720) 555-2245',
            address: null,
            city: null,
            state: null,
            zipCode: null,
            memberType: 'newsletter_subscriber',
            status: 'inactive',
            interests: JSON.stringify(['ministry_updates']),
            notes: 'Subscribed via website 03/2024. Unsubscribed 10/2024.',
            joinedAt: new Date('2024-03-18').toISOString(),
            lastActivityAt: new Date('2024-10-10').toISOString(),
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-10-10').toISOString(),
        },

        // Registered Users (5 members)
        {
            userId: null,
            firstName: 'Christopher',
            lastName: 'Young',
            email: 'christopher.young@gmail.com',
            phone: '(303) 555-2356',
            address: '1567 Logan St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80203',
            memberType: 'registered_user',
            status: 'active',
            interests: JSON.stringify(['spiritual_growth', 'community_events', 'recovery_support']),
            notes: 'Active in prayer wall. Attends virtual Bible studies. United Convicts participant. 18 months recovery.',
            joinedAt: new Date('2024-06-15').toISOString(),
            lastActivityAt: new Date('2024-12-22').toISOString(),
            createdAt: new Date('2024-06-15').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            userId: null,
            firstName: 'Jessica',
            lastName: 'Hernandez',
            email: 'jessica.hernandez@gmail.com',
            phone: '(720) 555-2467',
            address: '2890 Park Ave',
            city: 'Denver',
            state: 'CO',
            zipCode: '80205',
            memberType: 'registered_user',
            status: 'active',
            interests: JSON.stringify(['volunteer_opportunities', 'spiritual_growth', 'community_events']),
            notes: 'Registered user since April. Very engaged in community platform. Interested in becoming volunteer.',
            joinedAt: new Date('2024-04-10').toISOString(),
            lastActivityAt: new Date('2024-12-21').toISOString(),
            createdAt: new Date('2024-04-10').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            userId: null,
            firstName: 'Anthony',
            lastName: 'Scott',
            email: 'anthony.scott@gmail.com',
            phone: '(303) 555-2578',
            address: '4123 High St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80211',
            memberType: 'registered_user',
            status: 'active',
            interests: JSON.stringify(['recovery_support', 'spiritual_growth', 'volunteer_opportunities']),
            notes: 'Active platform user. Shares testimonies regularly. 2 years in recovery. Powerful testimony of transformation.',
            joinedAt: new Date('2024-02-28').toISOString(),
            lastActivityAt: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            userId: null,
            firstName: 'Nicole',
            lastName: 'Green',
            email: 'nicole.green@yahoo.com',
            phone: '(720) 555-2689',
            address: '567 Emerson St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80218',
            memberType: 'registered_user',
            status: 'active',
            interests: JSON.stringify(['community_events', 'spiritual_growth', 'volunteer_opportunities']),
            notes: 'Registered user since May. Attends monthly community gatherings. Strong prayer warrior.',
            joinedAt: new Date('2024-05-18').toISOString(),
            lastActivityAt: new Date('2024-12-19').toISOString(),
            createdAt: new Date('2024-05-18').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            userId: null,
            firstName: 'Kevin',
            lastName: 'Adams',
            email: 'kevin.adams@gmail.com',
            phone: '(303) 555-2790',
            address: '890 Washington St',
            city: 'Denver',
            state: 'CO',
            zipCode: '80203',
            memberType: 'registered_user',
            status: 'inactive',
            interests: JSON.stringify(['spiritual_growth', 'recovery_support']),
            notes: 'Registered user since January. Last activity September 2024. Relocated out of state.',
            joinedAt: new Date('2024-01-25').toISOString(),
            lastActivityAt: new Date('2024-09-15').toISOString(),
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
    ];

    await db.insert(members).values(sampleMembers);
    
    console.log('✅ Members seeder completed successfully - 30 diverse UCon Ministries community members added');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});