import { db } from '../index';
import { partnerOrganizations } from '../schema';

export async function seedPartners() {
  console.log('🌱 Seeding partner organizations...');

  const partners = [
    // Educational Partners (5)
    {
      name: 'Community College of Denver',
      category: 'educational',
      description: 'Vocational training and GED programs for individuals seeking education and career advancement.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-b7a95e50-20251114060310.jpg',
      websiteUrl: 'https://www.ccd.edu',
      contactEmail: 'partnerships@ccd.edu',
      partnershipType: 'service_provider',
      servicesProvided: ['GED Programs', 'Vocational Training', 'Career Counseling'],
      isActive: true,
      isFeatured: true,
      partnershipStartDate: '2024-01-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Denver Public Library',
      category: 'educational',
      description: 'Free computer access, job search resources, and adult literacy programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-b7a95e50-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Computer Access', 'Job Resources', 'Literacy Programs'],
      isActive: true,
      partnershipStartDate: '2024-02-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Emily Griffith Technical College',
      category: 'educational',
      description: 'Technical and trade skills training programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-b7a95e50-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Trade Skills', 'Technical Training', 'Certifications'],
      isActive: true,
      partnershipStartDate: '2024-03-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'University of Denver - Continuing Education',
      category: 'educational',
      description: 'Professional development and continuing education courses.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-b7a95e50-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Professional Development', 'Continuing Education', 'Leadership Training'],
      isActive: true,
      partnershipStartDate: '2024-04-05',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Denver School of the Arts',
      category: 'educational',
      description: 'Creative arts education and expression programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-b7a95e50-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Arts Education', 'Creative Expression', 'Performance Arts'],
      isActive: true,
      partnershipStartDate: '2024-05-20',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // Justice Partners (4)
    {
      name: 'Colorado Legal Services',
      category: 'justice',
      description: 'Free legal aid for low-income individuals and families navigating the justice system.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-37949567-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Legal Aid', 'Court Navigation', 'Expungement Services'],
      isActive: true,
      isFeatured: true,
      partnershipStartDate: '2024-01-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Denver Re-entry Project',
      category: 'justice',
      description: 'Comprehensive reentry support for individuals returning from incarceration.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-37949567-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Reentry Support', 'Housing Assistance', 'Employment Placement'],
      isActive: true,
      partnershipStartDate: '2024-02-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Second Chance Center',
      category: 'justice',
      description: 'Record clearing and criminal justice advocacy.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-37949567-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Record Clearing', 'Legal Advocacy', 'Court Support'],
      isActive: true,
      partnershipStartDate: '2024-03-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Justice Reform Coalition',
      category: 'justice',
      description: 'Policy advocacy and systemic justice reform initiatives.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-37949567-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Policy Advocacy', 'Community Organizing', 'Legal Education'],
      isActive: true,
      partnershipStartDate: '2024-04-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // Healthcare Partners (6)
    {
      name: 'Denver Health',
      category: 'healthcare',
      description: 'Comprehensive medical and mental health services for underserved communities.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-a483b373-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Medical Care', 'Mental Health Services', 'Substance Abuse Treatment'],
      isActive: true,
      isFeatured: true,
      partnershipStartDate: '2024-01-05',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Colorado Coalition for the Homeless - Healthcare',
      category: 'healthcare',
      description: 'Healthcare services specifically for individuals experiencing homelessness.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-a483b373-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Medical Care', 'Dental Services', 'Behavioral Health'],
      isActive: true,
      partnershipStartDate: '2024-02-20',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Mental Health Center of Denver',
      category: 'healthcare',
      description: 'Specialized mental health and addiction treatment programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-a483b373-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Therapy', 'Addiction Treatment', 'Crisis Intervention'],
      isActive: true,
      partnershipStartDate: '2024-03-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Community Health Services',
      category: 'healthcare',
      description: 'Primary care and preventive health services.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-a483b373-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Primary Care', 'Preventive Services', 'Health Education'],
      isActive: true,
      partnershipStartDate: '2024-04-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Rocky Mountain Crisis Partners',
      category: 'healthcare',
      description: 'Crisis mental health intervention and support services.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-a483b373-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Crisis Intervention', '24/7 Hotline', 'Emergency Services'],
      isActive: true,
      partnershipStartDate: '2024-05-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Addiction Recovery Centers of Colorado',
      category: 'healthcare',
      description: 'Comprehensive addiction treatment and recovery support.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-a483b373-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Detox Services', 'Inpatient Treatment', 'Outpatient Support'],
      isActive: true,
      partnershipStartDate: '2024-06-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // Business Partners (15)
    {
      name: 'King Soopers',
      category: 'business',
      description: 'Employment opportunities in retail and grocery operations.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Job Placement', 'Skills Training', 'Career Development'],
      isActive: true,
      isFeatured: true,
      partnershipStartDate: '2024-01-20',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Safeway',
      category: 'business',
      description: 'Grocery retail employment and skills development.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Job Opportunities', 'Training Programs'],
      isActive: true,
      partnershipStartDate: '2024-02-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Denver Metro Chamber of Commerce',
      category: 'business',
      description: 'Business networking and employment connections.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Job Fairs', 'Business Connections', 'Career Resources'],
      isActive: true,
      partnershipStartDate: '2024-03-05',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Goodwill of Colorado',
      category: 'business',
      description: 'Job training, employment services, and retail opportunities.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Job Training', 'Employment Placement', 'Retail Jobs'],
      isActive: true,
      partnershipStartDate: '2024-04-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Amazon Denver Fulfillment Center',
      category: 'business',
      description: 'Warehouse and logistics employment opportunities.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Warehouse Jobs', 'Benefits Package', 'Career Advancement'],
      isActive: true,
      partnershipStartDate: '2024-05-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Chipotle Mexican Grill',
      category: 'business',
      description: 'Restaurant and hospitality employment.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Restaurant Jobs', 'Management Training', 'Flexible Scheduling'],
      isActive: true,
      partnershipStartDate: '2024-06-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Home Depot',
      category: 'business',
      description: 'Retail and trade skills employment.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Retail Jobs', 'Trade Skills', 'Employee Benefits'],
      isActive: true,
      partnershipStartDate: '2024-07-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Starbucks',
      category: 'business',
      description: 'Coffee shop employment and management opportunities.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Barista Jobs', 'Management Track', 'College Tuition'],
      isActive: true,
      partnershipStartDate: '2024-07-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Target',
      category: 'business',
      description: 'Retail employment and career advancement.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Retail Jobs', 'Leadership Development', 'Benefits'],
      isActive: true,
      partnershipStartDate: '2024-08-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Walmart',
      category: 'business',
      description: 'Retail and logistics employment opportunities.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Retail Jobs', 'Distribution Jobs', 'Career Pathways'],
      isActive: true,
      partnershipStartDate: '2024-08-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Panera Bread',
      category: 'business',
      description: 'Restaurant and food service employment.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Food Service Jobs', 'Management Training'],
      isActive: true,
      partnershipStartDate: '2024-09-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Costco Wholesale',
      category: 'business',
      description: 'Wholesale retail employment with strong benefits.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Retail Jobs', 'Competitive Wages', 'Healthcare Benefits'],
      isActive: true,
      partnershipStartDate: '2024-09-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'RTD (Regional Transportation District)',
      category: 'business',
      description: 'Transportation services employment opportunities.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Driver Jobs', 'Maintenance Jobs', 'Union Benefits'],
      isActive: true,
      partnershipStartDate: '2024-10-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Xcel Energy',
      category: 'business',
      description: 'Utility services and skilled trades employment.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Skilled Trades', 'Technical Jobs', 'Benefits Package'],
      isActive: true,
      partnershipStartDate: '2024-10-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Comcast',
      category: 'business',
      description: 'Telecommunications and technical services employment.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-1ac4716c-20251114060310.jpg',
      partnershipType: 'employer',
      servicesProvided: ['Technical Jobs', 'Customer Service', 'Training Programs'],
      isActive: true,
      partnershipStartDate: '2024-11-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // Social Services Partners (8)
    {
      name: 'Catholic Charities of Denver',
      category: 'social_services',
      description: 'Comprehensive social services including housing, food, and family support.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Housing Assistance', 'Food Programs', 'Family Services'],
      isActive: true,
      isFeatured: true,
      partnershipStartDate: '2024-01-08',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Denver Rescue Mission',
      category: 'social_services',
      description: 'Emergency shelter, meals, and recovery programs for those experiencing homelessness.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Emergency Shelter', 'Meals', 'Recovery Programs'],
      isActive: true,
      partnershipStartDate: '2024-02-05',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Food Bank of the Rockies',
      category: 'social_services',
      description: 'Food distribution and hunger relief programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Food Distribution', 'Hunger Relief', 'Nutrition Education'],
      isActive: true,
      partnershipStartDate: '2024-03-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Colorado Coalition for the Homeless',
      category: 'social_services',
      description: 'Housing services and homelessness prevention programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Housing First', 'Case Management', 'Healthcare'],
      isActive: true,
      partnershipStartDate: '2024-04-10',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Urban Peak',
      category: 'social_services',
      description: 'Youth homeless services and emergency shelter.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Youth Services', 'Emergency Shelter', 'Life Skills Training'],
      isActive: true,
      partnershipStartDate: '2024-05-15',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Metro Caring',
      category: 'social_services',
      description: 'Food assistance and resource navigation.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'service_provider',
      servicesProvided: ['Food Pantry', 'Resource Navigation', 'Community Support'],
      isActive: true,
      partnershipStartDate: '2024-06-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Brothers Redevelopment',
      category: 'social_services',
      description: 'Affordable housing and community development.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Affordable Housing', 'Community Development', 'Social Services'],
      isActive: true,
      partnershipStartDate: '2024-07-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Volunteers of America Colorado',
      category: 'social_services',
      description: 'Housing, health, and human services programs.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-denver-s-1532aae8-20251114060310.jpg',
      partnershipType: 'referral',
      servicesProvided: ['Housing Programs', 'Health Services', 'Veterans Support'],
      isActive: true,
      partnershipStartDate: '2024-08-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },

    // Faith Partners (12)
    {
      name: 'First Baptist Church of Denver',
      category: 'faith',
      description: 'Faith community providing spiritual support, volunteers, and facility access.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Spiritual Support', 'Volunteers', 'Facility Access'],
      isActive: true,
      isFeatured: true,
      partnershipStartDate: '2024-01-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Cathedral Basilica of the Immaculate Conception',
      category: 'faith',
      description: 'Catholic parish offering pastoral care and community outreach.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Pastoral Care', 'Community Outreach', 'Prayer Support'],
      isActive: true,
      partnershipStartDate: '2024-02-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Park Hill United Methodist Church',
      category: 'faith',
      description: 'Methodist congregation with active social justice ministry.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Social Justice Ministry', 'Community Programs', 'Volunteers'],
      isActive: true,
      partnershipStartDate: '2024-03-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Calvary Baptist Church',
      category: 'faith',
      description: 'Baptist church with recovery ministry and community services.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Recovery Ministry', 'Community Services', 'Spiritual Guidance'],
      isActive: true,
      partnershipStartDate: '2024-04-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Montview Boulevard Presbyterian Church',
      category: 'faith',
      description: 'Presbyterian church with mission outreach and social services.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Mission Outreach', 'Social Services', 'Food Programs'],
      isActive: true,
      partnershipStartDate: '2024-05-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Lighthouse Church',
      category: 'faith',
      description: 'Non-denominational church focused on community transformation.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Community Programs', 'Volunteer Network', 'Resource Sharing'],
      isActive: true,
      partnershipStartDate: '2024-06-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Grace Community Church',
      category: 'faith',
      description: 'Evangelical church with addiction recovery and family ministries.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Addiction Recovery', 'Family Ministry', 'Prayer Teams'],
      isActive: true,
      partnershipStartDate: '2024-07-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'St. John\'s Episcopal Cathedral',
      category: 'faith',
      description: 'Episcopal cathedral with urban ministry and social justice focus.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Urban Ministry', 'Social Justice', 'Community Partnerships'],
      isActive: true,
      partnershipStartDate: '2024-08-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Crossroads Church',
      category: 'faith',
      description: 'Multi-site church with homeless outreach and community care.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Homeless Outreach', 'Community Care', 'Volunteer Teams'],
      isActive: true,
      partnershipStartDate: '2024-09-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Solid Rock Community Church',
      category: 'faith',
      description: 'Church focused on reentry ministry and mentorship.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Reentry Ministry', 'Mentorship Programs', 'Support Groups'],
      isActive: true,
      partnershipStartDate: '2024-10-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'New Life Church',
      category: 'faith',
      description: 'Church with recovery celebration and life transformation focus.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Recovery Celebration', 'Life Groups', 'Mentorship'],
      isActive: true,
      partnershipStartDate: '2024-11-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      name: 'Faith Bible Chapel',
      category: 'faith',
      description: 'Bible-teaching church with compassion ministries.',
      logoUrl: 'https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/project-uploads/7735ca62-a0cb-4726-ab75-d41677168806/generated_images/professional-corporate-logo-for-colorado-2a728e5b-20251114060310.jpg',
      partnershipType: 'collaborative',
      servicesProvided: ['Compassion Ministry', 'Community Care', 'Resource Sharing'],
      isActive: true,
      partnershipStartDate: '2024-12-01',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  try {
    await db.insert(partnerOrganizations).values(partners);
    console.log(`✅ Successfully seeded ${partners.length} partner organizations`);
  } catch (error) {
    console.error('❌ Error seeding partners:', error);
    throw error;
  }
}
