import { db } from '@/db';
import { ucmLevelPermissions, ucmLevels } from '@/db/schema';
import { asc } from 'drizzle-orm';

async function main() {
    await db.delete(ucmLevelPermissions);
    console.log('🧹 Cleared existing permissions');

    const levelsResult = await db.select().from(ucmLevels).orderBy(asc(ucmLevels.level));
    
    if (levelsResult.length === 0) {
        throw new Error('No UCM levels found in database. Please run levels seeder first.');
    }

    const levelsByLevel: Record<number, number> = {};
    levelsResult.forEach(level => {
        levelsByLevel[level.level] = level.id;
    });

    console.log('📋 Retrieved UCM levels:', levelsByLevel);

    const permissions = [
        { ucmLevelId: levelsByLevel[1], resource: 'members', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'members', action: 'create' },
        { ucmLevelId: levelsByLevel[1], resource: 'members', action: 'update' },
        { ucmLevelId: levelsByLevel[1], resource: 'members', action: 'delete' },
        { ucmLevelId: levelsByLevel[1], resource: 'members', action: 'export' },
        { ucmLevelId: levelsByLevel[1], resource: 'convicts', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'convicts', action: 'create' },
        { ucmLevelId: levelsByLevel[1], resource: 'convicts', action: 'update' },
        { ucmLevelId: levelsByLevel[1], resource: 'convicts', action: 'delete' },
        { ucmLevelId: levelsByLevel[1], resource: 'convicts', action: 'export' },
        { ucmLevelId: levelsByLevel[1], resource: 'workshops', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'workshops', action: 'create' },
        { ucmLevelId: levelsByLevel[1], resource: 'workshops', action: 'update' },
        { ucmLevelId: levelsByLevel[1], resource: 'workshops', action: 'delete' },
        { ucmLevelId: levelsByLevel[1], resource: 'workshops', action: 'manage_participants' },
        { ucmLevelId: levelsByLevel[1], resource: 'workshops', action: 'host' },
        { ucmLevelId: levelsByLevel[1], resource: 'sessions', action: 'engage' },
        { ucmLevelId: levelsByLevel[1], resource: 'sessions', action: 'facilitate' },
        { ucmLevelId: levelsByLevel[1], resource: 'sessions', action: 'moderate' },
        { ucmLevelId: levelsByLevel[1], resource: 'attendance', action: 'view_attendance' },
        { ucmLevelId: levelsByLevel[1], resource: 'attendance', action: 'take_attendance' },
        { ucmLevelId: levelsByLevel[1], resource: 'attendance', action: 'manage_attendance' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'create' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'update' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'coordinate' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'field_work' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'resource_distribution' },
        { ucmLevelId: levelsByLevel[1], resource: 'outreach', action: 'community_liaison' },
        { ucmLevelId: levelsByLevel[1], resource: 'ministry', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'ministry', action: 'support' },
        { ucmLevelId: levelsByLevel[1], resource: 'ministry', action: 'teach' },
        { ucmLevelId: levelsByLevel[1], resource: 'ministry', action: 'disciple' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'counsel' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'pray_support' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'crisis_intervention' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'spiritual_guidance' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'visit' },
        { ucmLevelId: levelsByLevel[1], resource: 'pastoral', action: 'sacramental' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'assess' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'peer_support' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'refer' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'document_confidential' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'safety_plan' },
        { ucmLevelId: levelsByLevel[1], resource: 'mental_health', action: 'resource_connect' },
        { ucmLevelId: levelsByLevel[1], resource: 'volunteers', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'volunteers', action: 'review' },
        { ucmLevelId: levelsByLevel[1], resource: 'volunteers', action: 'approve' },
        { ucmLevelId: levelsByLevel[1], resource: 'volunteers', action: 'assign' },
        { ucmLevelId: levelsByLevel[1], resource: 'events', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'events', action: 'create' },
        { ucmLevelId: levelsByLevel[1], resource: 'events', action: 'update' },
        { ucmLevelId: levelsByLevel[1], resource: 'events', action: 'delete' },
        { ucmLevelId: levelsByLevel[1], resource: 'events', action: 'manage_registrations' },
        { ucmLevelId: levelsByLevel[1], resource: 'content', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'content', action: 'create' },
        { ucmLevelId: levelsByLevel[1], resource: 'content', action: 'publish' },
        { ucmLevelId: levelsByLevel[1], resource: 'content', action: 'delete' },
        { ucmLevelId: levelsByLevel[1], resource: 'prayers', action: 'read' },
        { ucmLevelId: levelsByLevel[1], resource: 'prayers', action: 'moderate' },
        { ucmLevelId: levelsByLevel[1], resource: 'prayers', action: 'reply' },
        { ucmLevelId: levelsByLevel[1], resource: 'system', action: 'manage_roles' },
        { ucmLevelId: levelsByLevel[1], resource: 'system', action: 'manage_permissions' },
        { ucmLevelId: levelsByLevel[1], resource: 'system', action: 'view_analytics' },
        { ucmLevelId: levelsByLevel[1], resource: 'system', action: 'manage_settings' },

        { ucmLevelId: levelsByLevel[2], resource: 'members', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'members', action: 'create' },
        { ucmLevelId: levelsByLevel[2], resource: 'members', action: 'update' },
        { ucmLevelId: levelsByLevel[2], resource: 'members', action: 'delete' },
        { ucmLevelId: levelsByLevel[2], resource: 'members', action: 'export' },
        { ucmLevelId: levelsByLevel[2], resource: 'convicts', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'convicts', action: 'create' },
        { ucmLevelId: levelsByLevel[2], resource: 'convicts', action: 'update' },
        { ucmLevelId: levelsByLevel[2], resource: 'convicts', action: 'delete' },
        { ucmLevelId: levelsByLevel[2], resource: 'convicts', action: 'export' },
        { ucmLevelId: levelsByLevel[2], resource: 'workshops', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'workshops', action: 'create' },
        { ucmLevelId: levelsByLevel[2], resource: 'workshops', action: 'update' },
        { ucmLevelId: levelsByLevel[2], resource: 'workshops', action: 'delete' },
        { ucmLevelId: levelsByLevel[2], resource: 'workshops', action: 'manage_participants' },
        { ucmLevelId: levelsByLevel[2], resource: 'workshops', action: 'host' },
        { ucmLevelId: levelsByLevel[2], resource: 'sessions', action: 'engage' },
        { ucmLevelId: levelsByLevel[2], resource: 'sessions', action: 'facilitate' },
        { ucmLevelId: levelsByLevel[2], resource: 'sessions', action: 'moderate' },
        { ucmLevelId: levelsByLevel[2], resource: 'attendance', action: 'view_attendance' },
        { ucmLevelId: levelsByLevel[2], resource: 'attendance', action: 'take_attendance' },
        { ucmLevelId: levelsByLevel[2], resource: 'attendance', action: 'manage_attendance' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'create' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'update' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'coordinate' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'field_work' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'resource_distribution' },
        { ucmLevelId: levelsByLevel[2], resource: 'outreach', action: 'community_liaison' },
        { ucmLevelId: levelsByLevel[2], resource: 'ministry', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'ministry', action: 'support' },
        { ucmLevelId: levelsByLevel[2], resource: 'ministry', action: 'teach' },
        { ucmLevelId: levelsByLevel[2], resource: 'ministry', action: 'disciple' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'counsel' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'pray_support' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'crisis_intervention' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'spiritual_guidance' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'visit' },
        { ucmLevelId: levelsByLevel[2], resource: 'pastoral', action: 'sacramental' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'assess' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'peer_support' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'refer' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'document_confidential' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'safety_plan' },
        { ucmLevelId: levelsByLevel[2], resource: 'mental_health', action: 'resource_connect' },
        { ucmLevelId: levelsByLevel[2], resource: 'volunteers', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'volunteers', action: 'review' },
        { ucmLevelId: levelsByLevel[2], resource: 'volunteers', action: 'approve' },
        { ucmLevelId: levelsByLevel[2], resource: 'volunteers', action: 'assign' },
        { ucmLevelId: levelsByLevel[2], resource: 'events', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'events', action: 'create' },
        { ucmLevelId: levelsByLevel[2], resource: 'events', action: 'update' },
        { ucmLevelId: levelsByLevel[2], resource: 'events', action: 'delete' },
        { ucmLevelId: levelsByLevel[2], resource: 'events', action: 'manage_registrations' },
        { ucmLevelId: levelsByLevel[2], resource: 'content', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'content', action: 'create' },
        { ucmLevelId: levelsByLevel[2], resource: 'content', action: 'publish' },
        { ucmLevelId: levelsByLevel[2], resource: 'content', action: 'delete' },
        { ucmLevelId: levelsByLevel[2], resource: 'prayers', action: 'read' },
        { ucmLevelId: levelsByLevel[2], resource: 'prayers', action: 'moderate' },
        { ucmLevelId: levelsByLevel[2], resource: 'prayers', action: 'reply' },
        { ucmLevelId: levelsByLevel[2], resource: 'system', action: 'view_analytics' },
        { ucmLevelId: levelsByLevel[2], resource: 'system', action: 'manage_settings' },

        { ucmLevelId: levelsByLevel[3], resource: 'members', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'members', action: 'create' },
        { ucmLevelId: levelsByLevel[3], resource: 'members', action: 'update' },
        { ucmLevelId: levelsByLevel[3], resource: 'members', action: 'delete' },
        { ucmLevelId: levelsByLevel[3], resource: 'members', action: 'export' },
        { ucmLevelId: levelsByLevel[3], resource: 'convicts', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'convicts', action: 'create' },
        { ucmLevelId: levelsByLevel[3], resource: 'convicts', action: 'update' },
        { ucmLevelId: levelsByLevel[3], resource: 'workshops', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'workshops', action: 'create' },
        { ucmLevelId: levelsByLevel[3], resource: 'workshops', action: 'update' },
        { ucmLevelId: levelsByLevel[3], resource: 'workshops', action: 'delete' },
        { ucmLevelId: levelsByLevel[3], resource: 'workshops', action: 'manage_participants' },
        { ucmLevelId: levelsByLevel[3], resource: 'workshops', action: 'host' },
        { ucmLevelId: levelsByLevel[3], resource: 'sessions', action: 'engage' },
        { ucmLevelId: levelsByLevel[3], resource: 'sessions', action: 'facilitate' },
        { ucmLevelId: levelsByLevel[3], resource: 'sessions', action: 'moderate' },
        { ucmLevelId: levelsByLevel[3], resource: 'attendance', action: 'view_attendance' },
        { ucmLevelId: levelsByLevel[3], resource: 'attendance', action: 'take_attendance' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'create' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'update' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'coordinate' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'field_work' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'resource_distribution' },
        { ucmLevelId: levelsByLevel[3], resource: 'outreach', action: 'community_liaison' },
        { ucmLevelId: levelsByLevel[3], resource: 'ministry', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'ministry', action: 'support' },
        { ucmLevelId: levelsByLevel[3], resource: 'ministry', action: 'teach' },
        { ucmLevelId: levelsByLevel[3], resource: 'ministry', action: 'disciple' },
        { ucmLevelId: levelsByLevel[3], resource: 'pastoral', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'pastoral', action: 'counsel' },
        { ucmLevelId: levelsByLevel[3], resource: 'pastoral', action: 'pray_support' },
        { ucmLevelId: levelsByLevel[3], resource: 'pastoral', action: 'crisis_intervention' },
        { ucmLevelId: levelsByLevel[3], resource: 'pastoral', action: 'spiritual_guidance' },
        { ucmLevelId: levelsByLevel[3], resource: 'pastoral', action: 'visit' },
        { ucmLevelId: levelsByLevel[3], resource: 'mental_health', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'mental_health', action: 'assess' },
        { ucmLevelId: levelsByLevel[3], resource: 'mental_health', action: 'peer_support' },
        { ucmLevelId: levelsByLevel[3], resource: 'mental_health', action: 'safety_plan' },
        { ucmLevelId: levelsByLevel[3], resource: 'mental_health', action: 'refer' },
        { ucmLevelId: levelsByLevel[3], resource: 'mental_health', action: 'resource_connect' },
        { ucmLevelId: levelsByLevel[3], resource: 'volunteers', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'volunteers', action: 'review' },
        { ucmLevelId: levelsByLevel[3], resource: 'volunteers', action: 'assign' },
        { ucmLevelId: levelsByLevel[3], resource: 'events', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'events', action: 'create' },
        { ucmLevelId: levelsByLevel[3], resource: 'events', action: 'update' },
        { ucmLevelId: levelsByLevel[3], resource: 'events', action: 'delete' },
        { ucmLevelId: levelsByLevel[3], resource: 'events', action: 'manage_registrations' },
        { ucmLevelId: levelsByLevel[3], resource: 'content', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'content', action: 'create' },
        { ucmLevelId: levelsByLevel[3], resource: 'prayers', action: 'read' },
        { ucmLevelId: levelsByLevel[3], resource: 'prayers', action: 'moderate' },
        { ucmLevelId: levelsByLevel[3], resource: 'prayers', action: 'reply' },

        { ucmLevelId: levelsByLevel[4], resource: 'members', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'members', action: 'create' },
        { ucmLevelId: levelsByLevel[4], resource: 'members', action: 'update' },
        { ucmLevelId: levelsByLevel[4], resource: 'convicts', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'convicts', action: 'create' },
        { ucmLevelId: levelsByLevel[4], resource: 'convicts', action: 'update' },
        { ucmLevelId: levelsByLevel[4], resource: 'workshops', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'workshops', action: 'host' },
        { ucmLevelId: levelsByLevel[4], resource: 'sessions', action: 'engage' },
        { ucmLevelId: levelsByLevel[4], resource: 'sessions', action: 'facilitate' },
        { ucmLevelId: levelsByLevel[4], resource: 'attendance', action: 'view_attendance' },
        { ucmLevelId: levelsByLevel[4], resource: 'attendance', action: 'take_attendance' },
        { ucmLevelId: levelsByLevel[4], resource: 'outreach', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'outreach', action: 'create' },
        { ucmLevelId: levelsByLevel[4], resource: 'outreach', action: 'update' },
        { ucmLevelId: levelsByLevel[4], resource: 'outreach', action: 'field_work' },
        { ucmLevelId: levelsByLevel[4], resource: 'outreach', action: 'resource_distribution' },
        { ucmLevelId: levelsByLevel[4], resource: 'ministry', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'ministry', action: 'support' },
        { ucmLevelId: levelsByLevel[4], resource: 'ministry', action: 'teach' },
        { ucmLevelId: levelsByLevel[4], resource: 'pastoral', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'pastoral', action: 'pray_support' },
        { ucmLevelId: levelsByLevel[4], resource: 'pastoral', action: 'visit' },
        { ucmLevelId: levelsByLevel[4], resource: 'mental_health', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'mental_health', action: 'peer_support' },
        { ucmLevelId: levelsByLevel[4], resource: 'mental_health', action: 'refer' },
        { ucmLevelId: levelsByLevel[4], resource: 'mental_health', action: 'resource_connect' },
        { ucmLevelId: levelsByLevel[4], resource: 'volunteers', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'events', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'events', action: 'manage_registrations' },
        { ucmLevelId: levelsByLevel[4], resource: 'content', action: 'read' },
        { ucmLevelId: levelsByLevel[4], resource: 'prayers', action: 'read' },

        { ucmLevelId: levelsByLevel[5], resource: 'members', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'convicts', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'workshops', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'sessions', action: 'engage' },
        { ucmLevelId: levelsByLevel[5], resource: 'sessions', action: 'facilitate' },
        { ucmLevelId: levelsByLevel[5], resource: 'sessions', action: 'moderate' },
        { ucmLevelId: levelsByLevel[5], resource: 'attendance', action: 'view_attendance' },
        { ucmLevelId: levelsByLevel[5], resource: 'attendance', action: 'take_attendance' },
        { ucmLevelId: levelsByLevel[5], resource: 'outreach', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'outreach', action: 'field_work' },
        { ucmLevelId: levelsByLevel[5], resource: 'outreach', action: 'resource_distribution' },
        { ucmLevelId: levelsByLevel[5], resource: 'ministry', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'ministry', action: 'support' },
        { ucmLevelId: levelsByLevel[5], resource: 'pastoral', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'pastoral', action: 'pray_support' },
        { ucmLevelId: levelsByLevel[5], resource: 'mental_health', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'mental_health', action: 'peer_support' },
        { ucmLevelId: levelsByLevel[5], resource: 'mental_health', action: 'resource_connect' },
        { ucmLevelId: levelsByLevel[5], resource: 'events', action: 'read' },
        { ucmLevelId: levelsByLevel[5], resource: 'prayers', action: 'read' },
    ];

    const permissionsWithTimestamps = permissions.map(perm => ({
        ...perm,
        createdAt: new Date().toISOString(),
    }));

    await db.insert(ucmLevelPermissions).values(permissionsWithTimestamps);

    const totalPermissions = permissionsWithTimestamps.length;
    
    console.log('\n✅ UCM Level permissions seeder completed successfully');
    console.log(`\n📊 Total permissions created: ${totalPermissions}`);
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});